#page title
page_title                                : Rohit Mishra                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# Information About Yourself
your_name                                 : Rohit Mishra                                
your_link                                 : https://rohimsh.github.io                   
your_city                                 : Bangalore                                
email_address                             : rohimsh@hotmail.com
facebook_username                         : rohimshra                                          
instagram_username                        : rohimsh_
twitter_username                          : rohimsh
github_username                           : rohimsh
linkedin_username                         : rohimsh
google_play_id                            : 8232447978100239458 
profile_logo_icon                         : assets/profile_logo_icon.png


# About app
profile_name                                  : About Rohit Mishra
profile_description                           : Welcome to my page! This is the pathway to enter wormholes of my thoughts and ideas.

# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Software
    description                           : Software expertise that brings your projects to life, from concept to creation.
    fontawesome_icon_name                 : terminal
    
  - title                                 : Physics
    description                           : Exploring the fabric of the universe.  Time, Relativity, and Quantum Computing enthusiast.
    fontawesome_icon_name                 : wrench

  - title                                 : Design
    description                           : Designing with distinction. Curating aesthetics that resonate with discerning tastes.
    fontawesome_icon_name                 : palette

  - title                                 : Quotes
    description                           : Unveiling wisdom through philosophy. Crafting insightful quotes from contemplation.
    fontawesome_icon_name                 : feather

  - title                                 : Teach
    description                           : Simplifying learning. Sharing knowledge in a way that sticks, fostering understanding.
    fontawesome_icon_name                 : chalkboard
  
  - title                                 : AppDev
    description                           : Apps tailored to you. Developing solutions that stem from real-world needs.
    fontawesome_icon_name                 : microchip

  - title                                 : Research
    description                           : Delving into the depths. Researching Distributed Computing, Databases, and Cloud-based Microservices.
    fontawesome_icon_name                 : search

  - title                                 : Socialise
    description                           : Forging connections. Embracing late-night conversations with friends and intriguing minds.
    fontawesome_icon_name                 : hashtag

  - title                                 : Astronomy
    description                           : Cultivating a lifelong enchantment with Astronomy since childhood, ignited by countless moments of stargazing.

fontawesome_icon_name                 : space-shuttle


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/green_on_right.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#4c4e4f"
cover_overlay_transparency                : 0.7

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#200b4d"

profile_title_color                       : "#ffffff"
profile_price_color                       : "#ffffff"
profile_description_color                 : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
